# .github/labels.yml
# Agent assignment labels
- name: agent:codex
  color: 0e8a16
  description: Assign to Codex agent
- name: agent:copilot
  color: 1d76db
  description: Assign to Copilot

# Agent workflow labels
- name: agents
  color: fbca04
  description: Agent automation
- name: agents:activated
  color: ededed
  description: Agent has been activated
- name: agents:keepalive
  color: 1d76db
  description: Enable keepalive monitoring on PR
- name: agents:pause
  color: b60205
  description: Pause agent work
- name: agents:paused
  color: c2e0c6
  description: Pause keepalive for this PR
- name: agents:allow-change
  color: ededed
  description: Permit workflow edits when justification provided

# PR origin labels
- name: from:codex
  color: 0e8a16
  description: PR was created by or for Codex
- name: from:copilot
  color: 0366d6
  description: PR was created by or for Copilot

# Autofix labels
- name: autofix
  color: 0366d6
  description: Let bots format/lint automatically
- name: autofix:applied
  color: 7057ff
  description: Autofix was applied
- name: autofix:clean
  color: 0e8a16
  description: Autofix passed - no changes needed
- name: autofix:patch
  color: ededed
  description: Autofix patch available

# Automerge labels
- name: automerge
  color: 0052cc
  description: Eligible for auto-merge when checks pass

# Risk assessment labels
- name: risk:low
  color: 0e8a16
  description: Small, safe change (automerge candidate)
- name: risk:medium
  color: fbca04
  description: Moderate change
- name: risk:high
  color: d73a4a
  description: Large or sensitive change

# Status labels (used by agents)
- name: status:in-progress
  color: fbca04
  description: Agent work in progress
- name: status:ready
  color: 0052cc
  description: Ready for agent pickup

# Reminder label (for scheduled tasks)
- name: reminder
  color: d4c5f9
  description: Reminder for future action
