# .github/labels.yml
- name: from:codex
  color: 0e8a16
  description: PR was created by or for Codex
- name: from:copilot
  color: 0366d6
  description: PR was created by or for Copilot
- name: automerge
  color: 0052cc
  description: Eligible for auto-merge when checks pass
- name: risk:low
  color: 0e8a16
  description: Small, safe change (automerge candidate)
- name: risk:medium
  color: fbca04
  description: Moderate change
- name: risk:high
  color: d73a4a
  description: Large or sensitive change
- name: agent:codex
  color: 0e8a16
  description: Route this issue to Codex
- name: agent:copilot
  color: 0e8a16
  description: Route this issue to Copilot
- name: autofix
  color: 0366d6
  description: Let bots format/lint automatically
