N_SIMULATIONS: 1
N_MONTHS: 1
backend: numpy
analysis_mode: returns
external_pa_capital: 100.0
active_ext_capital: 50.0
internal_pa_capital: 150.0
total_fund_capital: 300.0
w_beta_H: 0.5
w_alpha_H: 0.5
theta_extpa: 0.5
active_share: 0.5
mu_H: 0.04
sigma_H: 0.01
mu_E: 0.05
sigma_E: 0.02
mu_M: 0.03
sigma_M: 0.02
rho_idx_H: 0.05
rho_idx_E: 0.0
rho_idx_M: 0.0
rho_H_E: 0.1
rho_H_M: 0.1
rho_E_M: 0.0
internal_financing_mean_month: 0.0
internal_financing_sigma_month: 0.0
internal_spike_prob: 0.0
internal_spike_factor: 0.0
ext_pa_financing_mean_month: 0.0
ext_pa_financing_sigma_month: 0.0
ext_pa_spike_prob: 0.0
ext_pa_spike_factor: 0.0
act_ext_financing_mean_month: 0.0
act_ext_financing_sigma_month: 0.0
act_ext_spike_prob: 0.0
act_ext_spike_factor: 0.0
risk_metrics:
  - Return
  - Risk
  - ShortfallProb