from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


class BitGeneratorLike(Protocol):
    """Protocol for NumPy-style bit generator state handling."""

    state: Any


class GeneratorLike(Protocol):
    """Protocol for RNGs compatible with the simulation sampling interface."""

    bit_generator: BitGeneratorLike

    def normal(self, *args: Any, **kwargs: Any) -> Any: ...

    def random(self, *args: Any, **kwargs: Any) -> Any: ...

    def chisquare(self, *args: Any, **kwargs: Any) -> Any: ...

    def multivariate_normal(self, *args: Any, **kwargs: Any) -> Any: ...


@runtime_checkable
class ArrayLike(Protocol):
    """Protocol for array-likes (numpy/cupy compatible)."""

    @property
    def shape(self) -> tuple[int, ...]: ...

    @property
    def ndim(self) -> int: ...

    @property
    def size(self) -> int: ...

    def __array__(self, dtype: Any | None = ...) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __add__(self, other: Any) -> ArrayLike: ...
    def __radd__(self, other: Any) -> ArrayLike: ...
    def __sub__(self, other: Any) -> ArrayLike: ...
    def __rsub__(self, other: Any) -> ArrayLike: ...
    def __mul__(self, other: Any) -> ArrayLike: ...
    def __rmul__(self, other: Any) -> ArrayLike: ...
    def __lt__(self, other: Any) -> ArrayLike: ...
    def __le__(self, other: Any) -> ArrayLike: ...
    def __gt__(self, other: Any) -> ArrayLike: ...
    def __ge__(self, other: Any) -> ArrayLike: ...
