from pa_core.contracts import (
    SUMMARY_CVAR_CI95_HIGH_COLUMN,
    SUMMARY_CVAR_CI95_LOW_COLUMN,
    SUMMARY_CVAR_COLUMN,
    SUMMARY_CVAR_SE_COLUMN,
    SUMMARY_CVAR_TERMINAL_COLUMN,
    SUMMARY_TERMINAL_CVAR_CI95_HIGH_COLUMN,
    SUMMARY_TERMINAL_CVAR_CI95_LOW_COLUMN,
    SUMMARY_TERMINAL_CVAR_HALF_SAMPLE_DELTA_COLUMN,
    SUMMARY_TERMINAL_CVAR_SE_COLUMN,
)

CVAR_DIAGNOSTIC_COLUMNS = [
    SUMMARY_CVAR_COLUMN,
    SUMMARY_CVAR_SE_COLUMN,
    SUMMARY_CVAR_CI95_LOW_COLUMN,
    SUMMARY_CVAR_CI95_HIGH_COLUMN,
    SUMMARY_CVAR_TERMINAL_COLUMN,
    SUMMARY_TERMINAL_CVAR_SE_COLUMN,
    SUMMARY_TERMINAL_CVAR_CI95_LOW_COLUMN,
    SUMMARY_TERMINAL_CVAR_CI95_HIGH_COLUMN,
    SUMMARY_TERMINAL_CVAR_HALF_SAMPLE_DELTA_COLUMN,
]
