from pathlib import Path

from pa_core.schema import (
    export_schema_definitions,
    generate_parameter_dictionary,
    generate_schema_templates,
)


def test_export_schema_includes_aliases() -> None:
    payload = export_schema_definitions(schema="config")
    model = payload["models"]["ModelConfig"]
    fields = model["fields"]
    assert fields["N_SIMULATIONS"]["alias"] == "Number of simulations"
    assert "Active share" in fields["active_share"]["aliases"]


def test_templates_match_schema(tmp_path: Path) -> None:
    generate_schema_templates(tmp_path)
    template_dir = Path("templates")
    template_files = [
        "parameters_template.csv",
        "params_template.yaml",
        "scenario_template.yaml",
        "scenario_example.yaml",
    ]
    for filename in template_files:
        generated = (tmp_path / filename).read_text()
        committed = (template_dir / filename).read_text()
        assert generated == committed, (
            f"{filename} template drift detected; re-run "
            "`python -m pa_core.schema --generate-templates`."
        )


def test_parameter_dictionary_matches_schema(tmp_path: Path) -> None:
    output_path = tmp_path / "PARAMETER_DICTIONARY.md"
    generate_parameter_dictionary(output_path, schema="config")
    committed = Path("docs/guides/PARAMETER_DICTIONARY.md").read_text()
    generated = output_path.read_text()
    assert generated == committed, (
        "Parameter dictionary drift detected; re-run "
        "`python -m pa_core.schema --generate-parameter-dictionary`."
    )


def test_parameter_dictionary_has_generation_header(tmp_path: Path) -> None:
    output_path = tmp_path / "PARAMETER_DICTIONARY.md"
    generate_parameter_dictionary(output_path, schema="config")
    content = output_path.read_text()
    assert "Generated by `python -m pa_core.schema --generate-parameter-dictionary`" in content
