# .github/workflows/codex-kickoff.yml
name: Kick off Codex from issue label
on:
  issues:
    types: [labeled]
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  kickoff:
    if: contains(github.event.issue.labels.*.name, 'agent:codex') || contains(github.event.issue.labels.*.name, 'codex')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create kickoff marker
        run: |
          mkdir -p .gate_smoke
          printf "# Kickoff for issue #%s\n\nThis file just triggers the pipeline.\n" "${{ github.event.issue.number }}" > ".gate_smoke/issue-${{ github.event.issue.number }}.md"
      - name: Create draft PR on codex branch
        uses: peter-evans/create-pull-request@v6
        with:
          branch: codex/fix-${{ github.event.issue.number }}
          title: "Codex: Fix #${{ github.event.issue.number }} — ${{ github.event.issue.title }}"
          body: |
            Auto-created kickoff PR for Codex to work on issue #${{ github.event.issue.number }}.
            This will run Streamlined Codex Auto-Debug and post results.
          labels: from:codex,risk:low
          draft: true
          commit-message: "chore(codex): kickoff for #${{ github.event.issue.number }}"
