name: Route to Codex + Kickoff PR
on:
  issues:
    types: [opened, edited, labeled, reopened]
permissions:
  contents: write         # needed to create branch/commit via create-pull-request
  pull-requests: write
  issues: write

jobs:
  route-and-kick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decide whether to route to Codex
        id: decide
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body || "";
            const labels = issue.labels?.map(l => l.name) || [];
            const wantsByCheckbox = /- \[[xX]\]\s*Route to Codex/.test(body);
            const wantsByLabel    = labels.includes("agent:codex");
            const wants = wantsByCheckbox || wantsByLabel;

            core.setOutput("wants", wants ? "true" : "false");
            core.setOutput("has_label", wantsByLabel ? "true" : "false");
            core.setOutput("issue_number", issue.number.toString());
            core.setOutput("title", issue.title || "");

      - name: Ensure label exists (create if missing)
        if: steps.decide.outputs.wants == 'true' && steps.decide.outputs.has_label == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const number = Number("${{ steps.decide.outputs.issue_number }}");
            // Add the agent:codex label to the issue
            await github.rest.issues.addLabels({
              owner, repo, issue_number: number, labels: ["agent:codex"]
            });

      - name: Check if kickoff PR already exists
        id: check_pr
        if: steps.decide.outputs.wants == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = Number("${{ steps.decide.outputs.issue_number }}");
            const head = `codex/fix-${issue_number}`;
            // Try to find an open PR with that head
            const prs = await github.paginate(github.rest.pulls.list, {
              owner, repo, state: "open", per_page: 100
            });
            const match = prs.find(pr => (pr.head && pr.head.ref === head));
            core.setOutput("exists", match ? "true" : "false");

      - name: Create kickoff marker file
        if: steps.decide.outputs.wants == 'true' && steps.check_pr.outputs.exists != 'true'
        run: |
          mkdir -p .gate_smoke
          printf "# Kickoff for issue #%s\n\nThis file triggers Codex automation.\n" "${{ steps.decide.outputs.issue_number }}" > ".gate_smoke/issue-${{ steps.decide.outputs.issue_number }}.md"

      - name: Create or update draft PR
        if: steps.decide.outputs.wants == 'true' && steps.check_pr.outputs.exists != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: codex/fix-${{ steps.decide.outputs.issue_number }}
          title: "Codex: Fix #${{ steps.decide.outputs.issue_number }} — ${{ steps.decide.outputs.title }}"
          body: |
            Auto-created kickoff PR for Codex to work on issue #${{ steps.decide.outputs.issue_number }}.
            This will run your debugging/CI workflows and gather results.
          labels: from:codex,automerge,risk:low
          draft: true
          commit-message: "chore(codex): kickoff for #${{ steps.decide.outputs.issue_number }}"
