# .github/workflows/debug-on-failure.yml
name: Trigger Codex debug on CI failure
on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: [completed]
permissions:
  contents: write
  actions: write
  checks: read
  pull-requests: write
  issues: write
jobs:
  run-debug:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      DEBUG_WORKFLOW_FILE: ${{ vars.DEBUG_WORKFLOW_FILE || 'codex-auto-debug.yml' }}
    steps:
      - name: Dispatch Codex Auto-Debug on PR head
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            if (!run.pull_requests || !run.pull_requests.length) {
              console.log("No pull requests found for this workflow run. Exiting.");
              return;
            }
            const owner = context.repo.owner, repo = context.repo.repo;
            const prNum = run.pull_requests[0].number;
            const { data: pr } = await github.rest.pulls.get({owner, repo, pull_number: prNum});
            const headRef = pr.head.ref;

            const debugWorkflow = process.env.DEBUG_WORKFLOW_FILE;

            // Fire the configured debug workflow (supports workflow_dispatch)
            await github.rest.actions.createWorkflowDispatch({
              owner, repo,
              workflow_id: debugWorkflow,
              ref: headRef,
              inputs: { debug_mode: 'true' }
            });

            // Leave a nudge on the PR
            await github.rest.issues.createComment({
              owner, repo, issue_number: prNum,
              body: "CI failed. Kicked off **Streamlined Codex Auto-Debug** on `" + headRef + "`. A report will be attached. If only formatting, the autofix job may push changes."
            });
