name: Issue event tracer

on:
  issues:
    types: [opened, edited, labeled, assigned, reopened]

permissions:
  issues: write  # to post a comment

jobs:
  trace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { action, issue, label, sender } = context.payload;
            const summary = {
              action,
              actor: sender?.login,
              label: label?.name || null,
              labels_now: (issue.labels || []).map(l => l.name),
              assignees_now: (issue.assignees || []).map(a => a.login),
              run_id: context.runId,
            };
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: "🔎 Issue event tracer\n\n```json\n" + JSON.stringify(summary, null, 2) + "\n```"
            });
