# .github/workflows/label-route-to-codex.yml
name: Apply 'agent:codex' when requested
on:
  issues:
    types: [opened, edited, reopened]
permissions:
  issues: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const number = context.payload.issue.number;
            const body = context.payload.issue.body || "";
            const wants = /- \[[xX]\]\s*Route to Codex/.test(body);
            const label = "agent:codex";
            const labels = await github.rest.issues.listLabelsOnIssue({ owner, repo, issue_number: number });
            const has = labels.data.some(l => l.name === label);
            if (wants && !has) await github.rest.issues.addLabels({ owner, repo, issue_number: number, labels: [label] });
            if (!wants && has) await github.rest.issues.removeLabel({ owner, repo, issue_number: number, name: label }).catch(()=>{});
