name: Streamlined Codex Auto-Debug

on:
  workflow_dispatch:
# Explicit permissions for GitHub Actions
permissions:
  contents: write          # Push commits and access repository
  pull-requests: write     # Comment on PRs
  issues: write           # PR comments (PRs are issues)
  actions: read           # Access workflow artifacts
  checks: write           # Update check status

env:
  GH_TOKEN: ${{ secrets.CODEX_PAT || secrets.GITHUB_TOKEN }}
  
jobs:
  streamlined-debug:
    runs-on: ubuntu-latest
    # Run on Codex branches or when manually triggered
    if: >
      startsWith(github.head_ref, 'codex/') ||
      startsWith(github.ref_name, 'codex/') ||
      github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.CODEX_PAT || secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: 🚀 Run Streamlined Debug
      id: streamlined_debug
      run: |
        echo "Running streamlined debugging workflow..."
        exit_code=0
        if [ -f scripts/streamlined_debug.py ]; then
          python scripts/streamlined_debug.py
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "ERROR: streamlined_debug.py failed with exit code $exit_code" >&2
          fi
        else
          echo "ERROR: scripts/streamlined_debug.py not found!" >&2
          exit_code=2
        fi
        echo "streamlined_exit_code=$exit_code" >> $GITHUB_OUTPUT

    - name: 📊 Upload Streamlined Debug Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: streamlined-debug-report-${{ github.run_id }}
        path: streamlined_debug_report.md
        if-no-files-found: ignore

    - name: 🔍 Run Detailed Debug (if streamlined found issues)
      id: detailed_debug
      if: steps.streamlined_debug.outputs.streamlined_exit_code != '0'
      run: |
        echo "Streamlined debug found issues. Running detailed analysis..."
        python scripts/debug_codex_pr.py --branch=${{ github.head_ref || github.ref_name }} --report=detailed_debug_report.md --max-iterations=3 --commit
        echo "detailed_exit_code=$?" >> $GITHUB_OUTPUT

    - name: 📊 Upload Detailed Debug Report
      uses: actions/upload-artifact@v4
      if: steps.detailed_debug.outcome != 'skipped'
      with:
        name: detailed-debug-report-${{ github.run_id }}
        path: detailed_debug_report.md
        if-no-files-found: ignore

    - name: 💬 Comment Results on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.CODEX_PAT || secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');

          // Read streamlined report
          let streamlinedReport = '';
          try {
            streamlinedReport = fs.readFileSync('streamlined_debug_report.md', 'utf8');
          } catch (error) {
            streamlinedReport = '❌ Streamlined debug report generation failed';
            console.log('Streamlined report read error:', error);
          }

          // Read detailed report if it exists
          let detailedReport = '';
          try {
            detailedReport = fs.readFileSync('detailed_debug_report.md', 'utf8');
          } catch (error) {
            // Detailed report may not exist if streamlined debug passed
            console.log('No detailed report (this is normal if streamlined debug passed)');
          }

          // Determine overall status
          const streamlinedPassed = '${{ steps.streamlined_debug.outputs.streamlined_exit_code }}' === '0';
          const detailedRan = '${{ steps.detailed_debug.outcome }}' !== 'skipped';

          let statusEmoji = streamlinedPassed ? '🎉' : '⚠️';
          let statusText = streamlinedPassed ? 'All Checks Passed' : 'Issues Found';

          let comment = `## ${statusEmoji} Automated Codex Debugging Results - ${statusText}

          ### 🚀 Streamlined Debug Results
          ${streamlinedReport}
          `;

          if (detailedRan && detailedReport) {
            comment += `
          ### 🔍 Detailed Debug Results
          ${detailedReport}
          `;
          }

          comment += `
          ---
          *Debug workflow: Streamlined → ${streamlinedPassed ? 'Passed ✅' : 'Failed ❌'}${detailedRan ? ' → Detailed Analysis 🔍' : ''}*
          `;

          try {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            console.log('Successfully posted PR comment');
          } catch (error) {
            console.log('Failed to post PR comment:', error);
            core.setFailed(`Failed to post PR comment: ${error.message}`);
          }

    - name: 🤖 Auto-commit fixes if any
      if: >
        (steps.streamlined_debug.outputs.streamlined_exit_code == '0' ||
         steps.detailed_debug.outputs.detailed_exit_code == '0') &&
        github.event_name != 'workflow_dispatch' &&
        (github.event_name != 'pull_request' ||
         github.event.pull_request.head.repo.full_name == github.repository)
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Determine push branch and repo details
        REPO_FULL="${{ github.repository }}"
        HEAD_REPO_FULL="${{ github.event.pull_request.head.repo.full_name || github.repository }}"
        PUSH_BRANCH="${{ github.head_ref || github.ref_name }}"
        
        # Skip push for non-branch refs
        case "$PUSH_BRANCH" in
          refs/pull/*) echo "Skipping push: non-branch ref '$PUSH_BRANCH'"; exit 0 ;;
        esac

        # Double-check same-repo push safety
        if [ "$REPO_FULL" != "$HEAD_REPO_FULL" ]; then
          echo "ℹ️ Skipping auto-push for fork PR ($HEAD_REPO_FULL). Maintainer action required."
          exit 0
        fi

        # Check if there are changes to commit
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected, committing fixes..."
          git add .
          git commit -m "🤖 Auto-fix: Resolve Codex integration issues

          - Applied automatic formatting fixes
          - Resolved type compatibility issues
          - Cleaned up import statements
          - Fixed common integration patterns

          Generated by streamlined debugging workflow"

          # Use explicit token-authenticated URL to avoid credential/remote issues
          PUSH_URL="https://x-access-token:${{ env.GH_TOKEN }}@github.com/${REPO_FULL}"
          echo "Pushing to $REPO_FULL:$PUSH_BRANCH"
          if git push "$PUSH_URL" HEAD:"$PUSH_BRANCH"; then
            echo "✅ Successfully pushed auto-fixes"
          else
            echo "❌ Failed to push auto-fixes; check branch protections/permissions"
            echo "   Branch: $PUSH_BRANCH | Repo: $REPO_FULL"
            echo "   Hint: Ensure 'Allow GitHub Actions to bypass branch protections' is enabled if using protected branches."
            exit 1
          fi
        else
          echo "✅ No changes to commit - repository is already in good state"
        fi

    - name: 📋 Set final status
      if: always()
      run: |
        streamlined_code="${{ steps.streamlined_debug.outputs.streamlined_exit_code }}"
        detailed_code="${{ steps.detailed_debug.outputs.detailed_exit_code }}"

        if [ "$streamlined_code" = "0" ]; then
          echo "✅ Streamlined debug passed - all good!"
          exit 0
        elif [ "$detailed_code" = "0" ]; then
          echo "✅ Detailed debug resolved issues - all good!"
          exit 0
        else
          echo "⚠️ Issues remain that need manual attention"
          exit 1
        fi
